# -*- coding: utf-8 -*-
"""cifarNEW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvQryk2UUHUdRbmiojeegzhC_GBKAKOE
"""

from google.colab import files

files.upload()

!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

!kaggle datasets list

!kaggle competitions download -c cifar-10

!ls

!7z e train.7z

#importing libraries and performing EDA
import pandas as pd
import numpy as np
import os, shutil
import matplotlib.pyplot as plt
from matplotlib.image import imread
#original_train_set = '../input/cifar-10/train'
original_train_labels = 'trainLabels.csv'

#reading labels csv into python and parsing
f = open(original_train_labels)
data = f.read()
f.close()

lines = data.split('\n')
header = lines[0].split(',')
lines = lines[1:]
lines[1].split(',')
cols = []
for i in range (len(lines)):
    cols.append(lines[i].split(','))
    

print(header)

#extracting only the labels into a list
labels = [cols[i][1] for i in range(len(cols)-1)]

#converting data in dataframe
s1 = pd.Series(range(1,len(lines)), index = range(1,len(lines)), name = 'id')
s2 = pd.Series(labels,index = range(1,len(lines)), name = 'label')

df_labels = pd.concat([s1, s2], axis=1)
print(df_labels.head())
print(df_labels.tail())
unique_labels = df_labels.label.unique()
df_labels.label.value_counts() #this shows a uniform distribution of image classes
df_labels.label.value_counts().plot(kind ='bar')

#More Visualization- seeing first 9 images in the training dataset
import matplotlib.image as mpimg 
for i in range(1,10):
    plt.subplot(330 + 0 + i)
    #define filename
    filename = str(i) + '.png'
    #load image pixels
    image = mpimg.imread(filename)
    #plot the data
    plt.imshow(image)
plt.show()

# Mapping train images to labels in trainLabels
from pandas import read_csv

filename = 'trainLabels.csv'
map_csv = read_csv(filename)
print(map_csv.shape)

